-- OWN YOUR OPTIONS COLLECTIVE: COMPLETE SUPABASE DATABASE
-- Run once in the Supabase SQL Editor connected to the Own Your Options app.
-- April is the single owner. Add her user ID to oyo_app_owner after her account exists.

create extension if not exists pgcrypto;

create table if not exists public.oyo_app_owner (
  singleton boolean primary key default true check (singleton),
  user_id uuid not null unique references auth.users(id) on delete restrict,
  assigned_at timestamptz default now()
);

create or replace function public.oyo_is_owner()
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.oyo_app_owner where user_id = auth.uid()
  );
$$;

create table if not exists public.oyo_staff_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'moderator' check (role in ('moderator')),
  status text not null default 'Active' check (status in ('Active','Suspended')),
  assigned_by uuid references auth.users(id),
  assigned_at timestamptz default now(),
  notes text default ''
);

create or replace function public.oyo_is_moderator()
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.oyo_staff_roles
    where user_id = auth.uid() and role = 'moderator' and status = 'Active'
  );
$$;

create or replace function public.oyo_can_moderate()
returns boolean language sql stable security definer set search_path = public
as $$ select public.oyo_is_owner() or public.oyo_is_moderator(); $$;

create table if not exists public.oyo_member_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Own Your Options Member',
  province_state text default '',
  skills text[] default '{}',
  business_interests text[] default '{}',
  goals text[] default '{}',
  bio text default '',
  avatar_url text default '',
  directory_visible boolean default true,
  updated_at timestamptz default now()
);

create table if not exists public.oyo_memberships (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  plan text not null default 'Collective',
  status text not null default 'Active',
  status_reason text default '',
  blocked_at timestamptz,
  archived_at timestamptz,
  joined_at timestamptz default now(),
  last_active_at timestamptz default now(),
  admin_notes text default ''
);

create or replace function public.oyo_has_hub_access()
returns boolean language sql stable security definer set search_path = public
as $$
  select public.oyo_is_owner() or exists (
    select 1 from public.oyo_memberships
    where user_id = auth.uid() and status = 'Active'
  );
$$;

create table if not exists public.oyo_hub_content (
  id bigint generated by default as identity primary key,
  area text not null,
  type text not null,
  title text not null,
  description text default '',
  body text default '',
  status text not null default 'Draft',
  file_path text default '',
  external_url text default '',
  sort_order integer default 0,
  created_by uuid references auth.users(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.oyo_member_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id bigint not null references public.oyo_hub_content(id) on delete cascade,
  status text not null default 'Not started',
  percent integer not null default 0 check (percent between 0 and 100),
  reflection text default '',
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz default now(),
  unique(user_id, content_id)
);

create table if not exists public.oyo_community_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  space text not null,
  body text not null,
  image_path text default '',
  status text not null default 'Published',
  created_at timestamptz default now()
);

create table if not exists public.oyo_community_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.oyo_community_posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  status text not null default 'Published',
  created_at timestamptz default now()
);

create table if not exists public.oyo_event_registrations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id bigint not null references public.oyo_hub_content(id) on delete cascade,
  registered_at timestamptz default now(),
  attended boolean default false,
  unique(user_id, content_id)
);

alter table public.oyo_member_profiles enable row level security;
alter table public.oyo_app_owner enable row level security;
alter table public.oyo_staff_roles enable row level security;
alter table public.oyo_memberships enable row level security;
alter table public.oyo_hub_content enable row level security;
alter table public.oyo_member_progress enable row level security;
alter table public.oyo_community_posts enable row level security;
alter table public.oyo_community_comments enable row level security;
alter table public.oyo_event_registrations enable row level security;

create policy "members see visible directory profiles" on public.oyo_member_profiles
for select to authenticated using (public.oyo_has_hub_access() and (directory_visible or user_id = auth.uid() or public.oyo_is_owner()));
create policy "members update own profile" on public.oyo_member_profiles
for update to authenticated using (public.oyo_has_hub_access() and user_id = auth.uid()) with check (public.oyo_has_hub_access() and user_id = auth.uid());
create policy "owner manages profiles" on public.oyo_member_profiles
for all to authenticated using (public.oyo_is_owner()) with check (public.oyo_is_owner());

create policy "owner sees owner record" on public.oyo_app_owner
for select to authenticated using (user_id = auth.uid());
create policy "staff see own role" on public.oyo_staff_roles
for select to authenticated using (user_id = auth.uid() or public.oyo_is_owner());
create policy "owner assigns and removes moderators" on public.oyo_staff_roles
for all to authenticated using (public.oyo_is_owner()) with check (public.oyo_is_owner());

create policy "members see own membership" on public.oyo_memberships
for select to authenticated using (user_id = auth.uid() or public.oyo_is_owner());
create policy "owner manages memberships" on public.oyo_memberships
for all to authenticated using (public.oyo_is_owner()) with check (public.oyo_is_owner());

create policy "members read published hub content" on public.oyo_hub_content
for select to authenticated using (public.oyo_has_hub_access() and (status = 'Published' or public.oyo_is_owner()));
create policy "owner manages hub content" on public.oyo_hub_content
for all to authenticated using (public.oyo_is_owner()) with check (public.oyo_is_owner());

create policy "members manage own progress" on public.oyo_member_progress
for all to authenticated using (public.oyo_has_hub_access() and (user_id = auth.uid() or public.oyo_is_owner()))
with check (public.oyo_has_hub_access() and (user_id = auth.uid() or public.oyo_is_owner()));

create policy "members read published posts" on public.oyo_community_posts
for select to authenticated using (public.oyo_has_hub_access() and (status = 'Published' or user_id = auth.uid() or public.oyo_is_owner()));
create policy "members create own posts" on public.oyo_community_posts
for insert to authenticated with check (public.oyo_has_hub_access() and user_id = auth.uid());
create policy "members update own posts" on public.oyo_community_posts
for update to authenticated using (public.oyo_has_hub_access() and (user_id = auth.uid() or public.oyo_can_moderate()));
create policy "members remove own posts" on public.oyo_community_posts
for delete to authenticated using (public.oyo_has_hub_access() and (user_id = auth.uid() or public.oyo_can_moderate()));

create policy "members read published comments" on public.oyo_community_comments
for select to authenticated using (public.oyo_has_hub_access() and (status = 'Published' or user_id = auth.uid() or public.oyo_is_owner()));
create policy "members create own comments" on public.oyo_community_comments
for insert to authenticated with check (public.oyo_has_hub_access() and user_id = auth.uid());
create policy "members remove own comments" on public.oyo_community_comments
for delete to authenticated using (public.oyo_has_hub_access() and (user_id = auth.uid() or public.oyo_can_moderate()));

create policy "members manage own registrations" on public.oyo_event_registrations
for all to authenticated using (public.oyo_has_hub_access() and (user_id = auth.uid() or public.oyo_is_owner()))
with check (public.oyo_has_hub_access() and (user_id = auth.uid() or public.oyo_is_owner()));

insert into storage.buckets (id, name, public)
values ('oyo-hub-content', 'oyo-hub-content', false), ('oyo-community', 'oyo-community', false)
on conflict (id) do update set public = false;

create policy "members read hub files" on storage.objects
for select to authenticated using (public.oyo_has_hub_access() and bucket_id in ('oyo-hub-content','oyo-community'));
create policy "owner manages hub content files" on storage.objects
for all to authenticated using (bucket_id = 'oyo-hub-content' and public.oyo_is_owner())
with check (bucket_id = 'oyo-hub-content' and public.oyo_is_owner());
create policy "members upload community pictures" on storage.objects
for insert to authenticated with check (public.oyo_has_hub_access() and bucket_id = 'oyo-community' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "members manage own community pictures" on storage.objects
for delete to authenticated using (bucket_id = 'oyo-community' and ((storage.foldername(name))[1] = auth.uid()::text or public.oyo_can_moderate()));

create or replace function public.oyo_create_member_records()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.oyo_member_profiles (user_id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)))
  on conflict (user_id) do nothing;
  insert into public.oyo_memberships (user_id, email)
  values (new.id, new.email)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists oyo_on_auth_user_created on auth.users;
create trigger oyo_on_auth_user_created after insert on auth.users
for each row execute procedure public.oyo_create_member_records();

create or replace function public.oyo_set_member_access(
  target_user_id uuid,
  new_status text,
  reason text default ''
)
returns void language plpgsql security definer set search_path = public, auth
as $$
begin
  if not public.oyo_is_owner() then raise exception 'Owner access required'; end if;
  if exists (select 1 from public.oyo_app_owner where user_id = target_user_id) then
    raise exception 'The owner account cannot be blocked or archived';
  end if;
  if new_status not in ('Active','Blocked','Archived') then raise exception 'Invalid member status'; end if;
  update public.oyo_memberships
  set status = new_status,
      status_reason = reason,
      blocked_at = case when new_status = 'Blocked' then now() else null end,
      archived_at = case when new_status = 'Archived' then now() else null end
  where user_id = target_user_id;
  if new_status <> 'Active' then
    update public.oyo_member_profiles set directory_visible = false where user_id = target_user_id;
    update public.oyo_staff_roles set status = 'Suspended' where user_id = target_user_id;
  end if;
end;
$$;

create or replace function public.oyo_permanently_delete_member(target_user_id uuid)
returns void language plpgsql security definer set search_path = public, auth
as $$
begin
  if not public.oyo_is_owner() then raise exception 'Owner access required'; end if;
  if exists (select 1 from public.oyo_app_owner where user_id = target_user_id) then
    raise exception 'The owner account cannot be deleted';
  end if;
  if not exists (
    select 1 from public.oyo_memberships where user_id = target_user_id and status = 'Archived'
  ) then
    raise exception 'Archive the member before permanently deleting the account';
  end if;
  delete from auth.users where id = target_user_id;
end;
$$;

revoke all on function public.oyo_set_member_access(uuid,text,text) from public, anon, authenticated;
grant execute on function public.oyo_set_member_access(uuid,text,text) to authenticated;
revoke all on function public.oyo_permanently_delete_member(uuid) from public, anon, authenticated;
grant execute on function public.oyo_permanently_delete_member(uuid) to authenticated;

-- REQUIRED FINAL OWNER STEP:
-- Find April's UUID in Authentication > Users, paste it below, and run once.
-- This table allows exactly one owner account.
-- insert into public.oyo_app_owner (singleton, user_id)
-- values (true, 'APRIL-AUTH-USER-UUID')
-- on conflict (singleton) do update set user_id = excluded.user_id;
